/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Server;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-27T20:38:22.907Z[GMT]")
@Api(value = "createServer", description = "the createServer API", tags = { "createServer", })
public interface CreateServerApi {

    @ApiOperation(value = "Create a server object", nickname = "createServer", notes = "", tags = { "createServer", })
    @ApiResponses(value = { @ApiResponse(code = 201, message = "Server created successfully!") })
    @RequestMapping(value = "/createServer", consumes = { "application/json" }, method = RequestMethod.PUT)
    ResponseEntity<?> createServer(@ApiParam(value = "Server object", required = true) @Valid @RequestBody Server body);

}
