/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-27T20:38:22.907Z[GMT]")
@Api(value = "deleteServer", description = "the deleteServer API", tags = { "deleteServer", })
public interface DeleteServerApi {

    @ApiOperation(value = "Delete a server object", nickname = "deleteServer", notes = "", tags = { "deleteServer", })
    @ApiResponses(value = { @ApiResponse(code = 200, message = "Server deleted successfully!"), @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/deleteServer", method = RequestMethod.DELETE)
    ResponseEntity<?> deleteServer(
            @NotNull @ApiParam(value = "Server object that needs to be deleted", required = true) @Valid @RequestParam(value = "id", required = true) String id);

}
